version: '3'

services:
  gin-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root