version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql